### ISSUE TITLE
Missing v1.1.0 release on registry.terraform.io

### ISSUE THREAD

**Issue by drobakowski** [terraform-aws-modules/terraform-aws-customer-gateway#7]
Hi @antonbabenko,

I've trying to use this library in one of my project with terraform `0.13.2` and noticed that you already created a new release here on GitHub which seems to have support for that. Unfortunately this version is missing on the [Terraform Registry](https://registry.terraform.io/modules/terraform-aws-modules/customer-gateway/aws/1.0.0).

Could be so kind and publish this version?

Thanks and kind regards
David

**Comment by antonbabenko** [comment]
Hi @drobakowski !

There was a cache issue on the Terraform Registry side, I resynced it now and it worked - https://registry.terraform.io/modules/terraform-aws-modules/customer-gateway/aws/1.1.0

Closing this issue.

**Comment by drobakowski** [comment]
Thanks @antonbabenko!
