### ISSUE TITLE
Unable to pass sanity for  version above  >0.14

### ISSUE THREAD

**Issue by hatan4ik** [terraform-aws-modules/terraform-aws-customer-gateway#9]
Error: Unsupported Terraform Core version

  on .terraform/modules/ses-azure-us-route-based-gateway/versions.tf line 2, in terraform:
   2:   required_version = ">= 0.12.6, < 0.14"

Module module.ses-azure-us-route-based-gateway (from
terraform-aws-modules/customer-gateway/aws) does not support Terraform version
**0.14.7**. To proceed, either choose another supported Terraform version or
update this version constraint. Version constraints are normally set for good
reason, so updating the constraint may lead to other errors or unexpected
behavior.

Could you please update the module ?

**Comment by antonbabenko** [comment]
Please make sure you use v1.2.0 of this module which was released 3 months ago.

**Comment by hatan4ik** [comment]
Anton,
Thanks for your reply but I am getting following setup error:

  **source = "terraform-aws-modules/customer-gateway/aws"
  **version = "1.2.0"****

Running "terraform init" : 

Error: Unresolvable module version constraint
There is no available version of module
"terraform-aws-modules/customer-gateway/aws" (vpn.tf:5) which matches the
given version constraint. The newest available version is 1.1.0.

Changing to 1.1.0 getting error as reported last month.

What do I do wrong ?

**Comment by antonbabenko** [comment]
Thanks for the report. There was an issue with syncing of this module in the Terraform Registry.

Make sure you are using the correct versions - 1.2.0 or 1.3.0

[v1.3.0](https://github.com/terraform-aws-modules/terraform-aws-customer-gateway/releases/v1.3.0) has been just released.

**Comment by hatan4ik** [comment]
Thanks - using v1.3.0 now works fine.

Regards,
